development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: gastank
  pool: 5
  username: mike
  password: 12345
  host: localhost

test:
  database: gastanktest
  adapter: postgresql
  encoding: unicode
  host: localhost

